across(fix): remove padding from remove info
across-protocol/across-frontend pull request #148
Opened 2022-01-28 11:42 UTC by Gamaranto

Before: See pic in the story

After
<img width="456" alt="CleanShot 2022-01-28 at 12 37 07@2x" src="https://user-images.githubusercontent.com/29527327/151541133-24fd2be3-1b53-463b-8b1b-4297ab8537bd.png">

Signed-off-by: Gamaranto <francesco@umaproject.org>

2022-01-28 13:39 UTC, daywiss commented
looks like this is still missing space 
![image](https://user-images.githubusercontent.com/4429761/151556467-b5cd1590-32f2-48ba-86d1-e3d7ebfaa882.png)

2022-01-28 13:42 UTC, daywiss requested changes
leaving review so you can rerequest me, but see screenshot i left

2022-01-31 09:07 UTC, Gamaranto commented
> looks like this is still missing space ![image](https://user-images.githubusercontent.com/4429761/151556467-b5cd1590-32f2-48ba-86d1-e3d7ebfaa882.png)

great catch, fixed it

2022-01-31 13:07 UTC, daywiss approved these changes

2022-02-02 20:46 UTC, Tulun approved these changes

2022-02-03 21:20 UTC, merged