across(fix): change my deposit to position size
across-protocol/across-frontend pull request #149
Opened 2022-01-28 12:44 UTC by Gamaranto

Signed-off-by: Gamaranto <francesco@umaproject.org>

2022-01-28 13:21 UTC, daywiss requested changes
will need to update the var in position size

2022-01-28 13:21 UTC, daywiss commented on src/components/PoolForm/PoolForm.tsx
> +            {formatUnits(position.add(feesEarned), decimals).replace("-", "")}{" "}
just want to flag this, there is a value coming from the sdk already called `positionValue`. This is the variable we want in here, adding position and fees will produce a wrong value in some cases.

2022-01-28 13:26 UTC, daywiss commented on src/components/PoolForm/PoolForm.tsx
> +            {formatUnits(position.add(feesEarned), decimals).replace("-", "")}{" "}
https://github.com/across-protocol/across-frontend/blob/master/src/views/Pool.tsx#L124

2022-01-31 09:04 UTC, Gamaranto commented on src/components/PoolForm/PoolForm.tsx
> +            {formatUnits(position.add(feesEarned), decimals).replace("-", "")}{" "}
Thanks, fixed

2022-01-31 13:08 UTC, daywiss approved these changes

2022-01-31 13:26 UTC, merged