adding Matamo Analytics to Across
across-protocol/across-frontend pull request #150
Opened 2022-02-01 19:58 UTC by Tommy1231232

FYI directions on integrating Matamo:
<img width="1264" alt="Screen Shot 2022-02-01 at 2 57 58 PM" src="https://user-images.githubusercontent.com/71620056/152041907-0c1db871-74ae-43cf-8a83-78a7c27c368c.png">

2022-02-01 19:59 UTC, Tommy1231232 commented
Note - this is only for tracking page views.

2022-02-02 01:18 UTC, daywiss requested changes
this actually should just be included on the index.html page. this app is considered a "SPA" (single page application), so these files you have edited only represent pages conceptually. The whole app is actually rendered within index.html, linked here https://github.com/across-protocol/across-frontend/blob/AcrossAnalytics/public/index.html

2022-02-02 14:10 UTC, Tommy1231232 commented
> this actually should just be included on the index.html page. this app is considered a "SPA" (single page application), so these files you have edited only represent pages conceptually. The whole app is actually rendered within index.html, linked here https://github.com/across-protocol/across-frontend/blob/AcrossAnalytics/public/index.html

Thanks! I updated in another commit.

2022-02-02 14:30 UTC, daywiss commented on public/index.html
> +<script>
small nit, in the directions they say to paste this right before the closing head tag, that looks like `</head>`, so i think they want it right above this line: https://github.com/across-protocol/across-frontend/pull/150/files#diff-c2cc24bc9001b11b6add48a4cd8f893d5d6c6e4d1bd254158bd14ab997f552cdR56

2022-02-02 14:30 UTC, daywiss commented on src/views/About.tsx
> +
these mean an extra line was introduced, you can just delete the line

2022-02-02 14:30 UTC, daywiss commented on src/views/Pool.tsx
> +
same here

2022-02-02 19:24 UTC, Tommy1231232 commented on public/index.html
> +<script>
Thank you! Done

2022-02-02 19:24 UTC, Tommy1231232 commented on src/views/About.tsx
> +
Removed line

2022-02-02 19:25 UTC, Tommy1231232 commented on src/views/Pool.tsx
> +
Removed line

2022-02-03 02:01 UTC, daywiss commented on public/index.html
> +<script>
this script block (everything including `<script>...</script>` and inside) needs to be tabbed to line up with the `<title>` block above, just to keep things a bit neat. but outside of that looks ready to go

2022-02-03 19:17 UTC, Tommy1231232 commented on public/index.html
> +<script>
Updated. Thank you!

2022-02-03 19:31 UTC, daywiss approved these changes

2022-02-03 19:40 UTC, merged