Info modal
across-protocol/across-frontend pull request #43
Opened 2021-11-09 15:26 UTC by Gamaranto

**Motivation**
This PR adds the information modal and is bundled with 2 additional small UI improvements, it makes the footers on the Send and Pool tab sticky again and it add the "ticket" border to the accent section like in the designs

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [ ]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [ ]  Existing tests adequate, no new tests required
- [x]  All existing tests pass
- [ ]  Untested

2021-11-09 17:44 UTC, Tulun commented on src/components/SendAction/SendAction.styles.ts
>  `;
Should this be in rems?

2021-11-09 17:45 UTC, Tulun approved these changes
Minor nit, otherwise LGTM!

2021-11-10 01:47 UTC, daywiss requested changes
looks good just need to fix that link. also not sure if this got linted, i added a `yarn lint` script

2021-11-10 01:47 UTC, daywiss commented on src/components/InformationDialog/InformationDialog.tsx
> +            href="https://app.gitbook.com/o/-MlBqw0sVAJZO0pl5jGc/s/-MlBr3oaDzSVL5ybJHcV/how-does-across-work-1/architecture-process-walkthrough"
this takes me to a site where i need to log in, i dont think its right

2021-11-10 09:18 UTC, Gamaranto commented on src/components/SendAction/SendAction.styles.ts
>  `;
i think in general px values are better for spacing as they don't scale up with the user increasing their base font

2021-11-10 09:21 UTC, Gamaranto commented on src/components/InformationDialog/InformationDialog.tsx
> +            href="https://app.gitbook.com/o/-MlBqw0sVAJZO0pl5jGc/s/-MlBr3oaDzSVL5ybJHcV/how-does-across-work-1/architecture-process-walkthrough"
great catch!!

2021-11-10 16:26 UTC, daywiss approved these changes

2021-11-10 16:35 UTC, merged