feat(across): send funds from ethereum to optimism
across-protocol/across-frontend pull request #78
Opened 2021-12-09 01:37 UTC by amateima

2021-12-09 02:10 UTC, amateima commented on src/components/CoinSelection/CoinSelection.tsx
> +  const tokenBalanceMap = useMemo(() => {
`tokenList` supported by Optimism for deposits is not the same with `TOKENS_LIST`, this is why fetching balances by index doesn't work. I need to keep a map between tokens and balances. This is more of an improvisation and it has to be stored higher in the state

2021-12-09 15:20 UTC, daywiss commented
Might need to hold off until the send-diff-chains branch is merged to master. Then get the branch epic/l1tl2 branch reset to master, rebase and pr against that branch

2021-12-09 15:31 UTC, amateima commented
> Might need to hold off until the send-diff-chains branch is merged to master. Then get the branch epic/l1tl2 branch reset to master, rebase and pr against that branch

agree

2021-12-09 16:02 UTC, Tulun requested changes
Yeah I would say this is in a different epic. Re open this PR after we get the optimism stuff in from a different base.

2021-12-10 07:40 UTC, mrice32 commented
@amateima going to remove myself from review since we're gonna hold off on this PR. Feel free to re-add when you're ready for review!

2021-12-10 07:41 UTC, closed without merging